=== desibankproject/spring-kb/target/spring-kb/xml/mobile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.magic.com/mobile"
	xmlns:tns="http://www.magic.com/mobile" elementFormDefault="qualified">

	<!-- This is called global elements inside the schema -->
	 <element name="mobile" type="tns:Mobile"/> 
	 <element name="tmobile" type="tns:Mobile"/>
	 <element name="mobiles" type="tns:Mobiles"/>
	 
	  <complexType name="Mobiles">
	  		<sequence>
	  				<element name="mobile" type="tns:Mobile" minOccurs="0" maxOccurs="unbounded"/>
	  		</sequence>
	  </complexType>

	 <complexType name="Mobile">
	 		<sequence>
	 			  <element name="name" type="string" maxOccurs="1" minOccurs="1"/>
	 			  <element name="version" type="string"/>
	 			  <element name="price" type="float"/>
	 			  <element name="memory" type="string" minOccurs="1" maxOccurs="unbounded"/>
	 			  <element name="color" type="string"/>
	 			    <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
	 		</sequence>
	 </complexType>
	
</schema>

=== desibankproject/spring-kb/src/main/webapp/xml/mobiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<mobiles xmlns="http://www.magic.com/mobile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.magic.com/mobile mobile.xsd ">
	<mobile>
				<name>iPhone</name>
				<version>X</version>
				<price>9202</price>
				<memory>32GB</memory>
					<memory>16GB</memory>
				<memory>16GB</memory>
				<color>white</color>
				<description>iPhone really very nice mobile phone!</description>
	</mobile>
	
	<mobile>
				<name>Android</name>
				<version>3.2</version>
				<price>92</price>
				<memory>32GB</memory>
					<memory>4GB</memory>
				<memory>8GB</memory>
				<color>black</color>
				<description>Android really very nice mobile phone!</description>
	</mobile>
	
	<mobile>
				<name>iPhone</name>
				<version>X</version>
				<price>9202</price>
				<memory>32GB</memory>
					<memory>16GB</memory>
				<memory>16GB</memory>
				<color>white</color>
				<description>iPhone really very nice mobile phone!</description>
	</mobile>
	
</mobiles>
